runtime: python
env: flex

runtime_config:
  python_version: 3.12
  operation_system: "ubuntu22"

entrypoint: gunicorn -b :$PORT app.app:app

handler:
- url: /
  script: auto

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5